### ISSUE TITLE
.gitignnore PyCharm IDE support.

### ISSUE THREAD

**Issue by DeanChugall** [AaronWChen/MeaLeon#65]
Hello Aaron W Chen, 

It would be nice if .gitignore had support for development in the PyCharm IDE.

**Comment by AaronWChen** [comment]
Will investigate! I don't use Pycharm, is there a template .gitignore for Pycharm?

**Comment by DeanChugall** [comment]
Yea... it's in #66 .

**Comment by AaronWChen** [comment]
My bad, saw the issue but not the PR. Approved!
