### ISSUE TITLE
Multiple requirements.txt

### ISSUE THREAD

**Issue by DeanChugall** [AaronWChen/MeaLeon#67]
Question:
- Is it necessary to repeat requirements.txt for each environment *(**_Docker_**, **_PiP_**, **_Poetry_** ... etc.)?
-  It is not clear why **_PiP_** and **_Poetry_** are combined?

**Comment by AaronWChen** [comment]
Ah yes, this is legacy! The public, Heroku deployed version relied on pip, but dev branch is using poetry. Can possibly remove next commit, especially since Render can just use Poetry

**Comment by AaronWChen** [comment]
Did a hotfix on main to remove all the extra requirements.txt files! As well as the Dockerfile which never got used anyway
